name: gh-pages

on:
  push:
    paths:
    - 'src/**'
    - 'tools/**'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'svelte.config.js'
    - 'vite.config.js'
  pull_request:
      paths:
      - 'src/**'
      - 'tools/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'svelte.config.js'
      - 'vite.config.js'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '*'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm run build
        env:
          VITE_SITE_NAME: Demo Page
          VITE_WORDPRESS_VERSION: 6.0.0
          VITE_CONNECTION_TIMEOUT: 2000

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
